spring:
  cloud:
    config:
      server:
        composite:
          - type: kubernetes
  profiles:
    active: composite
  application:
    name: kubernetesconfigserver

server:
  port: 8888

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: "optional:kubernetes:"
